### ISSUE TITLE
代码拉下来报错  pom文件中的引入 版本是不是太高了

### ISSUE THREAD

**Issue by aermae** [TheBlindM/T-Shell#30]

**Comment by TheBlindM** [comment]
![image](https://user-images.githubusercontent.com/48701152/206114996-0dcbe6b3-dea3-4015-a3b5-ed8a3b7ae36e.png)

**Comment by TheBlindM** [comment]
项目 自带了maven

**Comment by aermae** [comment]
意思就是说 你那是不是版本太高了&nbsp; 看报的错是版本不匹配&nbsp; 我的jdk1.8
&nbsp;





&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年12月7日(星期三) 下午3:26
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [TheBlindM/T-Shell] 代码拉下来报错  pom文件中的引入 版本是不是太高了 (Issue #30)





 
项目 自带了maven

**Comment by TheBlindM** [comment]
> 

我的jdk19

**Comment by aermae** [comment]
🆗&nbsp; 那就对了&nbsp;&nbsp;&nbsp;





&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年12月7日(星期三) 下午3:30
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [TheBlindM/T-Shell] 代码拉下来报错  pom文件中的引入 版本是不是太高了 (Issue #30)





   
我的jdk19
