### ISSUE TITLE
提示网络不可用

### ISSUE THREAD

**Issue by QianYuyyds** [TheBlindM/T-Shell#33]
有网络却提示不可用

**Comment by TheBlindM** [comment]
请 检查ip端口或者密码是否正确

**Comment by hkthomas** [comment]
同样问题，新安装，新建组就提示网络不可用，还没到新建主机那一步呢。
![image](https://s1.ax1x.com/2023/01/12/pSu9ETJ.png)

**Comment by QianYuyyds** [comment]
没法设置组，打开软件就提示网络不可用

**Comment by TheBlindM** [comment]
> 没法设置组，打开软件就提示网络不可用

右键管理员启动
