### ISSUE TITLE
提示网络不可用。

### ISSUE THREAD

**Issue by hkthomas** [TheBlindM/T-Shell#37]
旧版之前新建过，也新建了主机，但无法连接。

卸载安装了最新的0.4.2，新建组就提示网络不可用。
图：
![image](https://s1.ax1x.com/2023/01/12/pSu9ETJ.png)

**Comment by TheBlindM** [comment]
> 刚发现，软件启动后，什么都不操作，过一会也会提示网络不可用。

装在C盘的话，要右键管理员启动

**Comment by hkthomas** [comment]
还真是。。

没想到这点。解决了。谢谢。

**Comment by TheBlindM** [comment]
> 还真是。。
> 
> 没想到这点。解决了。谢谢。

没事，因为readme还没完善
