### ISSUE TITLE
服务端运行报错

### ISSUE THREAD

**Issue by EvenYanghe** [TheBlindM/T-Shell#49]
ERROR] 源发行版 17 与 --enable-preview 一起使用时无效
  （仅发行版 19 支持预览语言功能）
[INFO] 1 error

**Comment by EvenYanghe** [comment]
[INFO] Compiling 149 source files to C:\Users\35705\Desktop\git\T-Shell\server\target\classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] 源发行版 17 与 --enable-preview 一起使用时无效
  （仅发行版 19 支持预览语言功能）
[INFO] 1 error
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  4.762 s
[INFO] Finished at: 2023-04-02T11:26:41+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal io.quarkus.platform:quarkus-maven-plugin:2.16.3.Final:dev (default-cli) on project demo1: Unable to execute mojo: Compilation failure
[ERROR] 源发行版 17 与 --enable-preview 一起使用时无效
[ERROR]   （仅发行版 19 支持预览语言功能）
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by TheBlindM** [comment]
要用jdk19运行



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年4月2日(周日) 中午11:27
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: Re: [TheBlindM/T-Shell] 服务端运行报错 (Issue #49)




 
[INFO] Compiling 149 source files to C:\Users\35705\Desktop\git\T-Shell\server\target\classes
 [INFO] -------------------------------------------------------------
 [ERROR] COMPILATION ERROR :
 [INFO] -------------------------------------------------------------
 [ERROR] 源发行版 17 与 --enable-preview 一起使用时无效
 （仅发行版 19 支持预览语言功能）
 [INFO] 1 error
 [INFO] -------------------------------------------------------------
 [INFO] ------------------------------------------------------------------------
 [INFO] BUILD FAILURE
 [INFO] ------------------------------------------------------------------------
 [INFO] Total time:  4.762 s
 [INFO] Finished at: 2023-04-02T11:26:41+08:00
 [INFO] ------------------------------------------------------------------------
 [ERROR] Failed to execute goal io.quarkus.platform:quarkus-maven-plugin:2.16.3.Final:dev (default-cli) on project demo1: Unable to execute mojo: Compilation failure
 [ERROR] 源发行版 17 与 --enable-preview 一起使用时无效
 [ERROR]   （仅发行版 19 支持预览语言功能）
 [ERROR] -&gt; [Help 1]
 [ERROR]
 [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
 [ERROR] Re-run Maven using the -X switch to enable full debug logging.
 [ERROR]
 [ERROR] For more information about the errors and possible solutions, please read the following articles:
 [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
