### ISSUE TITLE
有没有上传文件的功能

### ISSUE THREAD

**Issue by takumi-wu** [TheBlindM/T-Shell#6]

**Comment by TheBlindM** [comment]
有上传的啊，直接拖动上传的
![image](https://user-images.githubusercontent.com/48701152/199892798-9c57a07e-d884-4a90-82ec-4e6ba5776803.png)

**Comment by TheBlindM** [comment]
在这可以 查看 进度，不过0.1版本还没做相关的消息提示
![image](https://user-images.githubusercontent.com/48701152/199893271-e76a5feb-b563-46d3-a68b-d842b6adb642.png)
