### ISSUE TITLE
未使用过jdk19，如何来部署运行调试该项目

### ISSUE THREAD

**Issue by LiaoXH** [TheBlindM/T-Shell#60]
如标题，希望有一个友好的部署教学，感谢

**Comment by TheBlindM** [comment]
选择jdk19时，注意开启--enable-preview
![image](https://github.com/user-attachments/assets/338494c6-729c-4491-8bb0-d1239b3ec359)

如果你要打包 java 为exe 需要GraalVM
https://blog.csdn.net/qq_40495860/article/details/126542159


前端 用package.json中的appDev 来调试

**Comment by LiaoXH** [comment]
感谢指导

**Comment by LiaoXH** [comment]
前端是必须npm跑吗？还是也可以打包？这个我不是很了解；
把Java打成exe后，前端怎么打包为类似的？

**Comment by TheBlindM** [comment]
> 前端是必须npm跑吗？还是也可以打包？这个我不是很了解； 把Java打成exe后，前端怎么打包为类似的？

对，用package.json中的appBuild 来打包

**Comment by LiaoXH** [comment]
好。感谢大佬

**Comment by LiaoXH** [comment]
您好，请问下jdk19的graalVm是不是停止维护了，我在oracle官网没有找到19 graalvm的版本，您那边是否可以弄一个压缩包呢，jdk19版本的

**Comment by TheBlindM** [comment]
> 您好，请问下jdk19的graalVm是不是停止维护了，我在oracle官网没有找到19 graalvm的版本，您那边是否可以弄一个压缩包呢，jdk19版本的

你可以在这里面翻一番，https://github.com/graalvm/graalvm-ce-builds/releases

**Comment by TheBlindM** [comment]
> 您好，请问下jdk19的graalVm是不是停止维护了，我在oracle官网没有找到19 graalvm的版本，您那边是否可以弄一个压缩包呢，jdk19版本的

这是我本地的压缩包，不过我有一段时间没研究graalvm了。现在用rust来代替java native
https://airportal.cn/707398/gA8kfxF3RS 
取件码：707398

**Comment by LiaoXH** [comment]
感谢，不过这个连接好像过期了

**Comment by LiaoXH** [comment]
感谢，不过这个连接好像过期了

**Comment by TheBlindM** [comment]
> 感谢，不过这个连接好像过期了

那你就看这个https://github.com/graalvm/graalvm-ce-builds/releases 翻一番有jdk19的

**Comment by LiaoXH** [comment]
翻到了。。。谢谢
